# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12882ea6f0beace9cacc899e322daf843c75e6a5ab40c995f01c09d4c6650dfc809e2186be947305e0f408f62606c93b5e5e90b30be5b74fbc6ece44f06cba17

test:
  secret_key_base: 01986b8e6c2946b38a53a8f007fee26cf78f089096edcf14e7aca4e18a37a0022600260af75d81f6cbb8379fa16d38b5d79a987346af5ba617b93c915e9f5d77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
